### PR TITLE
Resolved missing categories that were not showing up.

### PR DESCRIPTION
**Pull request by rockstarartist**
Modified the categoryId() def to deal with no controlsets in page,
or when there is only one group per control set, or when there are
more control sets that there are groups (ie. groups that span more
than 2 rows.)

Please check with your presets.

### CODE REVIEW

**Comment by TheTechnobear** [comment]
thanks for this... 
do you have some example presets that shows this.i.e. an example with no controlsets.
it be useful to know if these are suppose to exist in the new schema or its a function of the conversion from v1 presets to v2

**Comment by TheTechnobear** [comment]
generally I don't think this control set mapping is going to work for the conversion process... it's too simplistic.

in reality controlsetid is actually pretty irrelevant. (since its not much more than a 'sub page')
what I really need to do is to find the group that the the control refers to.

unfortunately this is not possible in the schema.. 

the only way to do this is to make an assumption that the group label is position above the control. 
(this could be done by inspecting the bounds parameters)
however this can never be 100% ... since the groups are just visual indicators.
e.g. 
imagine row 1 has a group heading, and row 2 does not, there is nothing to say if row 2 is 'sub group' of row 1 or not.
the user only 'knows' because the context gives it away.

all that said... 
the goal of pre2inst.py is not a perfect conversion from preset to instrument.
(i knew from the outset this was not possible) 
rather its to provide an instrument file with the 'heavy lifting' done, that can then be edited.

the reason why I had to use group names at all, was because the name on the control is often repeated.
e.g. a synth with 2 filters, will have 2 controls called 'cutoff', one under filter 1 the other under filter 2
without the group name, when you read the instrument file, you had not ideas which was which.

**Comment by rockstarartist** [comment]
I totally get what you are saying. I felt that the way the controlsets were implemented is problematic. I am guessing it is still early with the development of the electra.one.

I also understand that the pre2inst.py is an imperfect solution to getting presets into instrument files. I made this change to solve a problem I had with the script, that perhaps others may have with it too. I probably didnt test my change as much as  I should have, and also should have pushed up a test case.

**Comment by TheTechnobear** [comment]
actually partly it was my misunderstanding of control sets...
I've been doing some more dev, and realised that control sets are merely a way to assign the encoders, as i said, kind of sub pages that we have the 3 buttons (on the left) to switch between.
they have no connection to position on screen, or groups....

what my recent dev is highlighting, is we/I should not get too hung up on the encoders (and so control sets), since I will be using the touch screen functionality much more. (this will become clearer when I show what Im up too ...) 

anyway... this is why Ive realised control sets are a bit of a red-herring, for the preset to instrument, it needs to really find the 'right' group by looking at position on screen.

perhaps the best (or at least one) solution, would be to only search for a group, where the control name is ambiguous, then use that purely for the name of the control in the instrument def

anyway, hopefully its 'good enough' for now.

what we really lack at the moment is an instrument definition editor.
the main issue I had with the instrument defs that are produced is that its a bit of a pain renaming things like categories, its a horrible search n' replace job, thats prone to error... similarly moving message between categories is not easy.
if this was simplified with an editor, then the 'less than perfect' translation would probably be less apparent :)

**Comment by rockstarartist** [comment]
agreed, an instrument definition editor would be great. I guess if the whole thing would have been done with an XML schema, or two, we could have just created an XSLT transformation template to change from one XML type to another, ie. from preset to instrument definition.

Yeah, through debugging why certain parts of my control types wouldnt get categorized is when I realized that the buttons were tied to the control sets which are allocated by every two horizontal rows of control types. 

right now, for me this script is very usable and I can create instrument definitions for some of my complex MIDI enabled eurorack modules to create better presets quicker.

**Pull request merged**
